/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshop;
import java.awt.HeadlessException;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author manish
 */
public class list extends javax.swing.JFrame {
Connection con; 
PreparedStatement pst;
PreparedStatement st;
ResultSet rs;
Choose ch=new Choose();
String name;
int a[]=new int[10];
int occ[]=new int[10];
    /**
     * Creates new form list
     */
    public list() {
        initComponents();
        this.setLocationRelativeTo(null);
        try{
           Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/book_store","root","");
           pst=con.prepareStatement("select * from user_data where Email=? and Password=?");
           String n=ch.username;
           String p=ch.pass2;
           pst.setString(1,n);
            pst.setString(2,p);
            rs=pst.executeQuery();
            if(rs.next()){
                name=rs.getString("First_Name");
                juser.setText("Welcome "+name);
            }
           
       }catch(HeadlessException | ClassNotFoundException | SQLException e){
           JOptionPane.showMessageDialog(null,e);
       }
        //For 1st Item
       jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jAutobiography1);
        jPanel2.repaint();
        jPanel2.revalidate();
        //For 2nd Item
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(jAutobiography2);
        jPanel3.repaint();
        jPanel3.revalidate();
        
         for(int i=0;i<10;i++){
            a[i]=0;
            occ[i]=0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Button_ViewCart = new javax.swing.JButton();
        juser = new javax.swing.JLabel();
        jRBAutobiography = new javax.swing.JRadioButton();
        jRBReligion = new javax.swing.JRadioButton();
        jRBEntrance = new javax.swing.JRadioButton();
        jRBHistory = new javax.swing.JRadioButton();
        jRBComputers = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jHistory_Politics1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Button_Renaissance = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        Spinner_Renaissance = new javax.swing.JSpinner();
        jLabel74 = new javax.swing.JLabel();
        jEntrance_exams1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Button_DC = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Spinner_DC = new javax.swing.JSpinner();
        jLabel76 = new javax.swing.JLabel();
        jReligion_Spirituality1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Button_Dalai = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Spinner_Dalai = new javax.swing.JSpinner();
        jLabel75 = new javax.swing.JLabel();
        jAutobiography1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Button_Paulo = new javax.swing.JButton();
        Spinner_Paulo = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jComputers1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Button_CCC = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        Spinner_CCC = new javax.swing.JSpinner();
        jLabel77 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jAutobiography2 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Button_Ramdev = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        Spinner_Ramdev = new javax.swing.JSpinner();
        jLabel78 = new javax.swing.JLabel();
        jReligion_Spirituality2 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        Button_Sadhguru = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        Spinner_Sadhguru = new javax.swing.JSpinner();
        jLabel79 = new javax.swing.JLabel();
        jEntrance_Exams2 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        Button_GMAT = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        Spinner_GMAT = new javax.swing.JSpinner();
        jLabel80 = new javax.swing.JLabel();
        jHistory_Politics2 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        Button_Republican = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        Spinner_Republican = new javax.swing.JSpinner();
        jLabel81 = new javax.swing.JLabel();
        jComputers2 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        Button_CAT = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        Spinner_CAT = new javax.swing.JSpinner();
        jLabel82 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 71, 71));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Categories");

        Button_ViewCart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_ViewCart.setText("View Cart");
        Button_ViewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ViewCartActionPerformed(evt);
            }
        });

        juser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        juser.setText("Welcome");

        buttonGroup1.add(jRBAutobiography);
        jRBAutobiography.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRBAutobiography.setText("Autobiographies");
        jRBAutobiography.setToolTipText("");
        jRBAutobiography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAutobiographyActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBReligion);
        jRBReligion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRBReligion.setText("Religion & Spirituality");
        jRBReligion.setToolTipText("");
        jRBReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBReligionActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBEntrance);
        jRBEntrance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRBEntrance.setText("Entrance Exams");
        jRBEntrance.setToolTipText("");
        jRBEntrance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEntranceActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBHistory);
        jRBHistory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRBHistory.setText("History & Politics");
        jRBHistory.setToolTipText("");
        jRBHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBHistoryActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBComputers);
        jRBComputers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRBComputers.setText("Computers");
        jRBComputers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBComputersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(juser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBComputers)
                            .addComponent(jRBHistory)
                            .addComponent(jRBEntrance)
                            .addComponent(jRBReligion)
                            .addComponent(jRBAutobiography)
                            .addComponent(Button_ViewCart, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(juser)
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRBAutobiography)
                .addGap(18, 18, 18)
                .addComponent(jRBReligion)
                .addGap(18, 18, 18)
                .addComponent(jRBEntrance)
                .addGap(18, 18, 18)
                .addComponent(jRBHistory)
                .addGap(18, 18, 18)
                .addComponent(jRBComputers)
                .addGap(99, 99, 99)
                .addComponent(Button_ViewCart, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        jHistory_Politics1.setBackground(new java.awt.Color(65, 131, 215));
        jHistory_Politics1.setToolTipText("");

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\manish\\Desktop\\oopm_project files\\book_data\\Renaissance.jpg")); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel24.setText("How to Run the World: Charting a Course to the Next Renaissance(Hardcover)");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel25.setText("By Parag Khanna ");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setText("Rs 839");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setText("Author:  Parag Khanna");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel28.setText("Language:  English");

        Button_Renaissance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_Renaissance.setText("Add To Cart");
        Button_Renaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RenaissanceActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel29.setText("Quantity");

        Spinner_Renaissance.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Spinner_Renaissance.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel74.setText(" Publisher:  Random House");

        javax.swing.GroupLayout jHistory_Politics1Layout = new javax.swing.GroupLayout(jHistory_Politics1);
        jHistory_Politics1.setLayout(jHistory_Politics1Layout);
        jHistory_Politics1Layout.setHorizontalGroup(
            jHistory_Politics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHistory_Politics1Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jHistory_Politics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(jHistory_Politics1Layout.createSequentialGroup()
                        .addGroup(jHistory_Politics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jHistory_Politics1Layout.createSequentialGroup()
                                .addGroup(jHistory_Politics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jHistory_Politics1Layout.createSequentialGroup()
                                        .addComponent(Button_Renaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel74, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Spinner_Renaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jHistory_Politics1Layout.setVerticalGroup(
            jHistory_Politics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
            .addGroup(jHistory_Politics1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel74)
                .addGap(30, 30, 30)
                .addGroup(jHistory_Politics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Renaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(Spinner_Renaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jHistory_Politics1, "card3");

        jEntrance_exams1.setBackground(new java.awt.Color(65, 131, 215));
        jEntrance_exams1.setToolTipText("");

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\manish\\Desktop\\oopm_project files\\book_data\\EntranceExam_DCPandey.jpg")); // NOI18N
        jLabel16.setText("jLabel16");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Understanding Physics for JEE Main & Advanced Optics & Modern Physics (Paperback) ");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("By Dc Pandey ");
        jLabel18.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("Rs 280");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setText("Author:  Dc Pandey ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setText("Language:  English");

        Button_DC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_DC.setText("Add To Cart");
        Button_DC.setToolTipText("");
        Button_DC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DCActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel22.setText("Quantity");

        Spinner_DC.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Spinner_DC.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel76.setText(" Publisher:  Arihant Publication");

        javax.swing.GroupLayout jEntrance_exams1Layout = new javax.swing.GroupLayout(jEntrance_exams1);
        jEntrance_exams1.setLayout(jEntrance_exams1Layout);
        jEntrance_exams1Layout.setHorizontalGroup(
            jEntrance_exams1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEntrance_exams1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jEntrance_exams1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jEntrance_exams1Layout.createSequentialGroup()
                        .addGroup(jEntrance_exams1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel76, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jEntrance_exams1Layout.createSequentialGroup()
                                .addComponent(Button_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Spinner_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jEntrance_exams1Layout.setVerticalGroup(
            jEntrance_exams1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEntrance_exams1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jEntrance_exams1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEntrance_exams1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel76)
                        .addGap(32, 32, 32)
                        .addGroup(jEntrance_exams1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_DC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(Spinner_DC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel2.add(jEntrance_exams1, "card2");

        jReligion_Spirituality1.setBackground(new java.awt.Color(65, 131, 215));
        jReligion_Spirituality1.setToolTipText("");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\manish\\Desktop\\oopm_project files\\book_data\\Dalai_Lama.jpg")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Stages of Meditation (Paperback)");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("By Kamalashila ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Rs 239");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("Author:  Kamalashila");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Language:  English");

        Button_Dalai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_Dalai.setText("Add To Cart");
        Button_Dalai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DalaiActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Quantity");

        Spinner_Dalai.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Spinner_Dalai.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel75.setText("Publisher:  Rider Books");

        javax.swing.GroupLayout jReligion_Spirituality1Layout = new javax.swing.GroupLayout(jReligion_Spirituality1);
        jReligion_Spirituality1.setLayout(jReligion_Spirituality1Layout);
        jReligion_Spirituality1Layout.setHorizontalGroup(
            jReligion_Spirituality1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReligion_Spirituality1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel9)
                .addGap(80, 80, 80)
                .addGroup(jReligion_Spirituality1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jReligion_Spirituality1Layout.createSequentialGroup()
                        .addComponent(Button_Dalai, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Spinner_Dalai, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jReligion_Spirituality1Layout.setVerticalGroup(
            jReligion_Spirituality1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReligion_Spirituality1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jReligion_Spirituality1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jReligion_Spirituality1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel75)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jReligion_Spirituality1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_Dalai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(Spinner_Dalai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel2.add(jReligion_Spirituality1, "card4");

        jAutobiography1.setBackground(new java.awt.Color(65, 131, 215));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\manish\\Desktop\\oopm_project files\\book_data\\paulo coelho.jpg")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("A Warriors Life - A Biography of Paulo Coelho (Paperback)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("By Fernando Morais");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Rs 539");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Author:  Fernando Morais");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Language:  English");

        Button_Paulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_Paulo.setText("Add To Cart");
        Button_Paulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PauloActionPerformed(evt);
            }
        });

        Spinner_Paulo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Spinner_Paulo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Quantity");

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel73.setText("Publisher:  HARPER COLLINS PUBLISHERS - UK");

        javax.swing.GroupLayout jAutobiography1Layout = new javax.swing.GroupLayout(jAutobiography1);
        jAutobiography1.setLayout(jAutobiography1Layout);
        jAutobiography1Layout.setHorizontalGroup(
            jAutobiography1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAutobiography1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jAutobiography1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAutobiography1Layout.createSequentialGroup()
                        .addComponent(Button_Paulo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Spinner_Paulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jAutobiography1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel73, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jAutobiography1Layout.setVerticalGroup(
            jAutobiography1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
            .addGroup(jAutobiography1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel73)
                .addGap(31, 31, 31)
                .addGroup(jAutobiography1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Paulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner_Paulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jAutobiography1, "card5");

        jComputers1.setBackground(new java.awt.Color(65, 131, 215));
        jComputers1.setToolTipText("");

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\manish\\Desktop\\oopm_project files\\book_data\\CCC.jpg")); // NOI18N

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel31.setText("Course On Computer Concept (CCC) (Paperback)");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel32.setText("By Satish Jain ");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel33.setText("Rs 127");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel34.setText("Author:  Satish Jain");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel35.setText("Language:  English");

        Button_CCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_CCC.setText("Add To Cart");
        Button_CCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CCCActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel36.setText("Quantity");

        Spinner_CCC.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Spinner_CCC.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel77.setText("Publisher:  BPB Publications");

        javax.swing.GroupLayout jComputers1Layout = new javax.swing.GroupLayout(jComputers1);
        jComputers1.setLayout(jComputers1Layout);
        jComputers1Layout.setHorizontalGroup(
            jComputers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jComputers1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(jComputers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jComputers1Layout.createSequentialGroup()
                        .addGroup(jComputers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel77, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jComputers1Layout.createSequentialGroup()
                                .addComponent(Button_CCC, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Spinner_CCC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jComputers1Layout.setVerticalGroup(
            jComputers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jComputers1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jComputers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jComputers1Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel35)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel77)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jComputers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_CCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(Spinner_CCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel30))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel2.add(jComputers1, "card6");

        jPanel3.setLayout(new java.awt.CardLayout());

        jAutobiography2.setBackground(new java.awt.Color(65, 131, 215));
        jAutobiography2.setToolTipText("");

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\manish\\Desktop\\oopm_project files\\book_data\\Baba Ramdev.jpg")); // NOI18N

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel38.setText("Godman to tycoon (Paperback)");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel39.setText("By Priyanka Pathak Narain ");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel40.setText("Rs 209");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel41.setText("Author:  Priyanka Pathak Narain");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel42.setText("Language:  English");

        Button_Ramdev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_Ramdev.setText("Add To Cart");
        Button_Ramdev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RamdevActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel43.setText("Quantity");

        Spinner_Ramdev.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Spinner_Ramdev.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel78.setText(" Publisher:  Juggernaut");

        javax.swing.GroupLayout jAutobiography2Layout = new javax.swing.GroupLayout(jAutobiography2);
        jAutobiography2.setLayout(jAutobiography2Layout);
        jAutobiography2Layout.setHorizontalGroup(
            jAutobiography2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAutobiography2Layout.createSequentialGroup()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jAutobiography2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAutobiography2Layout.createSequentialGroup()
                        .addComponent(Button_Ramdev, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Spinner_Ramdev, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel39)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jAutobiography2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel78, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jAutobiography2Layout.setVerticalGroup(
            jAutobiography2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jAutobiography2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39)
                .addGap(8, 8, 8)
                .addComponent(jLabel40)
                .addGap(13, 13, 13)
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel78)
                .addGap(24, 24, 24)
                .addGroup(jAutobiography2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Ramdev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(Spinner_Ramdev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jAutobiography2, "card2");

        jReligion_Spirituality2.setBackground(new java.awt.Color(65, 131, 215));
        jReligion_Spirituality2.setToolTipText("");

        jLabel44.setIcon(new javax.swing.ImageIcon("C:\\Users\\manish\\Desktop\\oopm_project files\\book_data\\Sadhguru.jpg")); // NOI18N

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel45.setText("Adiyogi: The Source of Yoga (Paperback)");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel46.setText("By Sadhguru ");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel47.setText("Rs 173");

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel48.setText("Author:  Sadhguru");

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel49.setText("Language:  English");

        Button_Sadhguru.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_Sadhguru.setText("Add To Cart");
        Button_Sadhguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SadhguruActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel50.setText("Quantity");

        Spinner_Sadhguru.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Spinner_Sadhguru.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel79.setText("Publisher:  Harpercollins Publishers India Pvt. Ltd.");

        javax.swing.GroupLayout jReligion_Spirituality2Layout = new javax.swing.GroupLayout(jReligion_Spirituality2);
        jReligion_Spirituality2.setLayout(jReligion_Spirituality2Layout);
        jReligion_Spirituality2Layout.setHorizontalGroup(
            jReligion_Spirituality2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReligion_Spirituality2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jReligion_Spirituality2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jReligion_Spirituality2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Button_Sadhguru, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Spinner_Sadhguru, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jReligion_Spirituality2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jReligion_Spirituality2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel79))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jReligion_Spirituality2Layout.setVerticalGroup(
            jReligion_Spirituality2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jReligion_Spirituality2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel79)
                .addGap(27, 27, 27)
                .addGroup(jReligion_Spirituality2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Sadhguru, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50)
                    .addComponent(Spinner_Sadhguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jReligion_Spirituality2, "card3");

        jEntrance_Exams2.setBackground(new java.awt.Color(65, 131, 215));

        jLabel51.setIcon(new javax.swing.ImageIcon("C:\\Users\\manish\\Desktop\\oopm_project files\\book_data\\EntanceExam_GMAT.jpg")); // NOI18N

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel52.setText("The Official Guide for GMAT Quantitative Review 2017 with Online Question Bank  ");

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel53.setText("and Exclusive Video (Paperback)");

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel54.setText("By Wiley ");

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel55.setText("Rs 635");

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel56.setText("Author:  Wiley");

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel57.setText("Language:  English");

        Button_GMAT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_GMAT.setText("Add To Cart");
        Button_GMAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GMATActionPerformed(evt);
            }
        });

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel58.setText("Quantity");

        Spinner_GMAT.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Spinner_GMAT.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel80.setText(" Publisher:  Wiley India Pvt. Ltd.");

        javax.swing.GroupLayout jEntrance_Exams2Layout = new javax.swing.GroupLayout(jEntrance_Exams2);
        jEntrance_Exams2.setLayout(jEntrance_Exams2Layout);
        jEntrance_Exams2Layout.setHorizontalGroup(
            jEntrance_Exams2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEntrance_Exams2Layout.createSequentialGroup()
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jEntrance_Exams2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(jEntrance_Exams2Layout.createSequentialGroup()
                        .addGroup(jEntrance_Exams2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jEntrance_Exams2Layout.createSequentialGroup()
                                .addGroup(jEntrance_Exams2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jEntrance_Exams2Layout.createSequentialGroup()
                                        .addComponent(Button_GMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Spinner_GMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel80))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jEntrance_Exams2Layout.setVerticalGroup(
            jEntrance_Exams2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jEntrance_Exams2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel80)
                .addGap(24, 24, 24)
                .addGroup(jEntrance_Exams2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_GMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58)
                    .addComponent(Spinner_GMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jEntrance_Exams2, "card4");

        jHistory_Politics2.setBackground(new java.awt.Color(65, 131, 215));

        jLabel59.setIcon(new javax.swing.ImageIcon("C:\\Users\\manish\\Desktop\\oopm_project files\\book_data\\Republican.jpg")); // NOI18N

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel60.setText("Republican Gomorrah: Inside the Movement That Shattered the Party (Hardcover)");

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel61.setText("By Max Blumenthal ");

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel62.setText("Rs 100");

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel63.setText("Author:  Max Blumenthal ");

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel64.setText("Language:  English");

        Button_Republican.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_Republican.setText("Add To Cart");
        Button_Republican.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RepublicanActionPerformed(evt);
            }
        });

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel65.setText("Quantity");

        Spinner_Republican.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Spinner_Republican.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel81.setText("Publisher:  Nation Books");

        javax.swing.GroupLayout jHistory_Politics2Layout = new javax.swing.GroupLayout(jHistory_Politics2);
        jHistory_Politics2.setLayout(jHistory_Politics2Layout);
        jHistory_Politics2Layout.setHorizontalGroup(
            jHistory_Politics2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHistory_Politics2Layout.createSequentialGroup()
                .addComponent(jLabel59)
                .addGap(39, 39, 39)
                .addGroup(jHistory_Politics2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel60)
                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jHistory_Politics2Layout.createSequentialGroup()
                        .addComponent(Button_Republican, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Spinner_Republican, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jHistory_Politics2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel81, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel64, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jHistory_Politics2Layout.setVerticalGroup(
            jHistory_Politics2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jHistory_Politics2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel61)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel63)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel81)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jHistory_Politics2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Republican, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65)
                    .addComponent(Spinner_Republican, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jPanel3.add(jHistory_Politics2, "card5");

        jComputers2.setBackground(new java.awt.Color(65, 131, 215));

        jLabel66.setIcon(new javax.swing.ImageIcon("C:\\Users\\manish\\Desktop\\oopm_project files\\book_data\\Computer_CAT.jpg")); // NOI18N

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel67.setText("Pearson Guide To Data Interpretation And Logical Reasoning For The CAT (Paperback)");

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel68.setText("By Nishit K Sinha ");

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel69.setText("Rs 438");

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel70.setText("Author: Nishit K Sinha ");

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel71.setText("Language:  English");

        Button_CAT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_CAT.setText("Add To Cart");
        Button_CAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CATActionPerformed(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel72.setText("Quantity");

        Spinner_CAT.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Spinner_CAT.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        Spinner_CAT.setToolTipText("");

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel82.setText("Publisher:  Dorling");

        javax.swing.GroupLayout jComputers2Layout = new javax.swing.GroupLayout(jComputers2);
        jComputers2.setLayout(jComputers2Layout);
        jComputers2Layout.setHorizontalGroup(
            jComputers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jComputers2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel66)
                .addGap(18, 18, 18)
                .addGroup(jComputers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jComputers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel71, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel70, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel69, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel68, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jComputers2Layout.createSequentialGroup()
                        .addComponent(Button_CAT, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Spinner_CAT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jComputers2Layout.setVerticalGroup(
            jComputers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jComputers2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jComputers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jComputers2Layout.createSequentialGroup()
                        .addComponent(jLabel67)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel68)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel69)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel70)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel71)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel82))
                    .addComponent(jLabel66))
                .addGap(1, 1, 1)
                .addGroup(jComputers2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_CAT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72)
                    .addComponent(Spinner_CAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel3.add(jComputers2, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 void updateTable(int qty,int pr,int n){
       
        pr+=qty*pr;
       try{
           Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/book_store","root","");
           pst=con.prepareStatement("update cart set Quantity=' "+n+" ',Price=' "+pr+" '");
           pst.executeUpdate();
       }catch(ClassNotFoundException | SQLException e){
           JOptionPane.showMessageDialog(null,e);
       }
    }
    
    
    private void jRBAutobiographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAutobiographyActionPerformed
        // TODO add your handling code here:
        //For 1st One
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jAutobiography1);
        jPanel2.repaint();
        jPanel2.revalidate();
        
        //For 2nd One
         jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(jAutobiography2);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jRBAutobiographyActionPerformed

    private void jRBReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBReligionActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jReligion_Spirituality1);
        jPanel2.repaint();
        jPanel2.revalidate();
        //Second
        
         jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(jReligion_Spirituality2);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jRBReligionActionPerformed

    private void jRBEntranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEntranceActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jEntrance_exams1);
        jPanel2.repaint();
        jPanel2.revalidate();
        //Second
          jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(jEntrance_Exams2);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jRBEntranceActionPerformed

    private void jRBHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBHistoryActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jHistory_Politics1);
        jPanel2.repaint();
        jPanel2.revalidate();
        //Second
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(jHistory_Politics2);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jRBHistoryActionPerformed

    private void jRBComputersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBComputersActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jComputers1);
        jPanel2.repaint();
        jPanel2.revalidate();
        //Second
         jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(jComputers2);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jRBComputersActionPerformed

    private void Button_ViewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ViewCartActionPerformed
        // TODO add your handling code here:
        Shopping_Cart sc=new Shopping_Cart();
        sc.setVisible(true);
        sc.pack();
        sc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_Button_ViewCartActionPerformed

    private void Button_PauloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PauloActionPerformed
        // TODO add your handling code here:
       
        String name="A Warriors Life - A Biography of Paulo Coelho",author="Paulo Coelho";
        int price=539;
        int q=Integer.parseInt(String.valueOf(Spinner_Paulo.getValue()));
        a[0]+=q;
        occ[0]=occ[0]+1;
        try{
            if(occ[0]>1){
               updateTable(q,price,a[0]); 
            }
            else
            {
            String query="insert into cart (Name, Author, Quantity, Price) values (?, ?, ?, ?)";
        st=con.prepareStatement(query);
        st.setString(1,"A Warriors Life - A Biography of Paulo Coelho (Paperback)");
        st.setString(2,"Paulo Coelho");
        st.setInt(3,q);
        st.setInt(4,539);
         st.execute();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        Shopping_Cart sc=new Shopping_Cart(name,author,q,price);
    }//GEN-LAST:event_Button_PauloActionPerformed

    private void Button_RamdevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RamdevActionPerformed
        // TODO add your handling code here:
        String name="Godman to tycoon",author="Priyanka Pathak Narain";
        int price=209;
        int q=Integer.parseInt(String.valueOf(Spinner_Ramdev.getValue()));
        a[1]=q;
        try{
        st=con.prepareStatement("insert into cart (Name, Author, Quantity, Price) values (?, ?, ?, ?)");
        st.setString(1,"Godman to tycoon (Paperback)");
        st.setString(2,"Priyanka Pathak Narain");
        st.setInt(3,q);
        st.setInt(4,209);
        st.execute();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
         new Shopping_Cart(name,author,q,price);
    }//GEN-LAST:event_Button_RamdevActionPerformed

    private void Button_DalaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DalaiActionPerformed
        // TODO add your handling code here:
        String name="Stages of Meditation",author="Kamalashila";
        int price=239;
         int q=Integer.parseInt(String.valueOf(Spinner_Dalai.getValue()));
         a[2]=q;
        try{
        st=con.prepareStatement("insert into cart (Name, Author, Quantity, Price) values (?, ?, ?, ?)");
        st.setString(1,"Stages of Meditation (Paperback)");
        st.setString(2,"Kamalashila");
        st.setInt(3,q);
        st.setInt(4,239);
        st.execute();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
         new Shopping_Cart(name,author,q,price);
    }//GEN-LAST:event_Button_DalaiActionPerformed

    private void Button_SadhguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SadhguruActionPerformed
        // TODO add your handling code here:
         String name="Adiyogi: The Source of Yoga",author="Sadhguru";
        int price=173;
        int q=Integer.parseInt(String.valueOf(Spinner_Sadhguru.getValue()));
        a[3]=q;
        try{
        st=con.prepareStatement("insert into cart (Name, Author, Quantity, Price) values (?, ?, ?, ?)");
        st.setString(1,"Adiyogi: The Source of Yoga (Paperback)");
        st.setString(2,"Sadhguru");
        st.setInt(3,q);
        st.setInt(4,173);
        st.execute();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
         new Shopping_Cart(name,author,q,price);
    }//GEN-LAST:event_Button_SadhguruActionPerformed

    private void Button_DCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DCActionPerformed
        // TODO add your handling code here:
         String name="Understanding Physics for JEE Main & Advanced Optics & Modern Physics",author="DC Pandey";
        int price=280;
         int q=Integer.parseInt(String.valueOf(Spinner_DC.getValue()));
         a[4]=q;
        try{
        st=con.prepareStatement("insert into cart (Name, Author, Quantity, Price) values (?, ?, ?, ?)");
        st.setString(1,"Understanding Physics for JEE Main & Advanced Optics & Modern Physics (Paperback) ");
        st.setString(2,"DC Pandey");
        st.setInt(3,q);
        st.setInt(4,280);
        st.execute();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
         new Shopping_Cart(name,author,q,price);
    }//GEN-LAST:event_Button_DCActionPerformed

    private void Button_GMATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GMATActionPerformed
        // TODO add your handling code here:
         String name="The Official Guide for GMAT Quantitative Review 2017 with Online Question Bank and Exclusive Video",author="Wiley";
        int price=635;
          int q=Integer.parseInt(String.valueOf(Spinner_GMAT.getValue()));
          a[5]=q;
        try{
        st=con.prepareStatement("insert into cart (Name, Author, Quantity, Price) values (?, ?, ?, ?)");
        st.setString(1,"The Official Guide for GMAT Quantitative Review 2017 with Online Question Bank and Exclusive Video (Paperback)");
        st.setString(2,"Wiley");
        st.setInt(3,q);
        st.setInt(4,635);
        st.execute();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
         new Shopping_Cart(name,author,q,price);
    }//GEN-LAST:event_Button_GMATActionPerformed

    private void Button_RenaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RenaissanceActionPerformed
        // TODO add your handling code here:
         String name="How to Run the World: Charting a Course to the Next Renaissance",author="Parag Khanna";
        int price=839;
         int q=Integer.parseInt(String.valueOf(Spinner_GMAT.getValue()));
         a[6]=q;
        try{
        st=con.prepareStatement("insert into cart (Name, Author, Quantity, Price) values (?, ?, ?, ?)");
        st.setString(1,"How to Run the World: Charting a Course to the Next Renaissance(Hardcover)");
        st.setString(2,"Parag Khanna");
        st.setInt(3,q);
        st.setInt(4,839);
        st.execute();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
         new Shopping_Cart(name,author,q,price);
    }//GEN-LAST:event_Button_RenaissanceActionPerformed

    private void Button_RepublicanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RepublicanActionPerformed
        // TODO add your handling code here:
         String name="Republican Gomorrah: Inside the Movement That Shattered the Party",author="Max Blumenthal";
        int price=100;
        int q=Integer.parseInt(String.valueOf(Spinner_GMAT.getValue()));
        a[7]=q;
        try{
        st=con.prepareStatement("insert into cart (Name, Author, Quantity, Price) values (?, ?, ?, ?)");
        st.setString(1,"Republican Gomorrah: Inside the Movement That Shattered the Party (Hardcover)");
        st.setString(2,"Max Blumenthal");
        st.setInt(3,q);
        st.setInt(4,100);
        st.execute();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
         new Shopping_Cart(name,author,q,price);
    }//GEN-LAST:event_Button_RepublicanActionPerformed

    private void Button_CCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CCCActionPerformed
        // TODO add your handling code here:
         String name="Course On Computer Concept (CCC)",author="Satish Jain";
        int price=127;
        int q=Integer.parseInt(String.valueOf(Spinner_GMAT.getValue()));
        a[8]=q;
        try{
        st=con.prepareStatement("insert into cart (Name, Author, Quantity, Price) values (?, ?, ?, ?)");
        st.setString(1,"Course On Computer Concept (CCC) (Paperback)");
        st.setString(2,"Satish Jain");
        st.setInt(3,q);
        st.setInt(4,127);
        st.execute();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
         new Shopping_Cart(name,author,q,price).setVisible(true);
    }//GEN-LAST:event_Button_CCCActionPerformed

    private void Button_CATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CATActionPerformed
        // TODO add your handling code here:
         String name="Pearson Guide To Data Interpretation And Logical Reasoning For The CAT",author="Nishit K Sinha";
        int price=438;
           int q=Integer.parseInt(String.valueOf(Spinner_GMAT.getValue()));
           a[9]=q;
        try{
        st=con.prepareStatement("insert into cart (Name, Author, Quantity, Price) values (?, ?, ?, ?)");
        st.setString(1,"Pearson Guide To Data Interpretation And Logical Reasoning For The CAT (Paperback)");
        st.setString(2,"Nishit K Sinha");
        st.setInt(3,q);
        st.setInt(4,438);
        st.execute();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
         new Shopping_Cart(name,author,q,price);
    }//GEN-LAST:event_Button_CATActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_CAT;
    private javax.swing.JButton Button_CCC;
    private javax.swing.JButton Button_DC;
    private javax.swing.JButton Button_Dalai;
    private javax.swing.JButton Button_GMAT;
    private javax.swing.JButton Button_Paulo;
    private javax.swing.JButton Button_Ramdev;
    private javax.swing.JButton Button_Renaissance;
    private javax.swing.JButton Button_Republican;
    private javax.swing.JButton Button_Sadhguru;
    private javax.swing.JButton Button_ViewCart;
    private javax.swing.JSpinner Spinner_CAT;
    private javax.swing.JSpinner Spinner_CCC;
    private javax.swing.JSpinner Spinner_DC;
    private javax.swing.JSpinner Spinner_Dalai;
    private javax.swing.JSpinner Spinner_GMAT;
    private javax.swing.JSpinner Spinner_Paulo;
    private javax.swing.JSpinner Spinner_Ramdev;
    private javax.swing.JSpinner Spinner_Renaissance;
    private javax.swing.JSpinner Spinner_Republican;
    private javax.swing.JSpinner Spinner_Sadhguru;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jAutobiography1;
    private javax.swing.JPanel jAutobiography2;
    private javax.swing.JPanel jComputers1;
    private javax.swing.JPanel jComputers2;
    private javax.swing.JPanel jEntrance_Exams2;
    private javax.swing.JPanel jEntrance_exams1;
    private javax.swing.JPanel jHistory_Politics1;
    private javax.swing.JPanel jHistory_Politics2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRBAutobiography;
    private javax.swing.JRadioButton jRBComputers;
    private javax.swing.JRadioButton jRBEntrance;
    private javax.swing.JRadioButton jRBHistory;
    private javax.swing.JRadioButton jRBReligion;
    private javax.swing.JPanel jReligion_Spirituality1;
    private javax.swing.JPanel jReligion_Spirituality2;
    private javax.swing.JLabel juser;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
