/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshop;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;
/**
 *
 * @author manish
 */
public class Shopping_Cart extends javax.swing.JFrame {
        Connection con;
        PreparedStatement pst;
        Statement st; 
        ResultSet rs;
        String name,author;
        int q,price;
        ArrayList<user> li=new ArrayList<>();
         int total=0;
         int a[]=new int[10];
         int occ[]=new int[10];
    
    /**
     * Creates new form Shopping_Cart
     */
    public Shopping_Cart() {
       
        initComponents();
        this.setLocationRelativeTo(null);
        try{
          Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/book_store","root","");
           pst=con.prepareStatement("select * from cart");
           rs=pst.executeQuery();
           user u;
           while(rs.next()){
               total+=(rs.getInt("Quantity")*rs.getInt("Price"));
               u=new user(rs.getString("Name"),rs.getString("Author"),rs.getInt("Quantity"),rs.getInt("Quantity")*rs.getInt("Price"));
               li.add(u);
           }
          // jTable.setModel(DbUtils.resultSetToTableModel(rs));
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
        Object row[]=new Object[4];
         DefaultTableModel model = (DefaultTableModel) jTable.getModel();
         for(int i=0;i<li.size();i++){
        row[0]=li.get(i).getName();
        row[1]=li.get(i).getAuthor();
        row[2]=li.get(i).getQuantity();
        row[3]=li.get(i).getPrice();
        model.addRow(row);
        jTextField1.setText(String.valueOf(total));
    }
          //model.addRow(new Object[]{name,author,quantity,(quantity*price)});
         //Vector v=new Vector();
         //v.add(name);
       // v.add(author);
       // v.add(quantity);
       // v.add(price*quantity);
        //model.addRow(v);
       
    }
    public Shopping_Cart(String n,String a,int q,int p){
        initComponents();
       this.name=n;
        this.author=a;
        this.q=q;
        this.price=p;
        addData();
       //Vector v=new Vector();
       // DefaultTableModel model =  (DefaultTableModel)  jTable.getModel();
       // v.add(name);
        //v.add(author);
       // v.add(quantity);
        //v.add(price*quantity);
       // model.addRow(v);
       //model.addRow(new Object[]{name,author,quantity,(quantity*price)});
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Button_checkout = new javax.swing.JButton();
        Button_backToList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        bRemove = new javax.swing.JButton();
        totalSum = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 71, 71));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Cart");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 275, 36));

        Button_checkout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_checkout.setText("Checkout");
        Button_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_checkoutActionPerformed(evt);
            }
        });
        jPanel1.add(Button_checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 20, 189, -1));

        Button_backToList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_backToList.setText("Back To Shopping");
        Button_backToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_backToListActionPerformed(evt);
            }
        });
        jPanel1.add(Button_backToList, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 176, -1));

        jTable.setAutoCreateRowSorter(true);
        jTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book", "Author", "Quantity", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setToolTipText("");
        jScrollPane1.setViewportView(jTable);

        bRemove.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bRemove.setText("Remove");
        bRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveActionPerformed(evt);
            }
        });

        totalSum.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        totalSum.setText("Price:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField1.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalSum, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRemove)
                    .addComponent(totalSum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void addData(){
      try{
          Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/book_store","root","");
           pst=con.prepareStatement("select * from cart");
           rs=pst.executeQuery();
          // jTable.setModel(DbUtils.resultSetToTableModel(rs));
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
    }
    
  
    
    private void Button_backToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_backToListActionPerformed
        // TODO add your handling code here:
        list l=new list();
        l.setVisible(true);
        l.pack();
        l.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_Button_backToListActionPerformed

    private void bRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable.getModel();
          
        total-=(Integer.parseInt(jTable.getValueAt(jTable.getSelectedRow(),3).toString()));
        
          jTextField1.setText(String.valueOf(total));
               try{
          Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/book_store","root","");
           int row=jTable.getSelectedRow();
           String val=model.getValueAt(row, 3).toString();
           pst=con.prepareStatement("delete  from cart where Price="+val);
           pst.executeUpdate();
          // jTable.setModel(DbUtils.resultSetToTableModel(rs));
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }
                model.removeRow(jTable.getSelectedRow());
    }//GEN-LAST:event_bRemoveActionPerformed

    private void Button_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_checkoutActionPerformed
        // TODO add your handling code here:
        Payment pm=new Payment(total);
        pm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_checkoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shopping_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shopping_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shopping_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shopping_Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shopping_Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_backToList;
    private javax.swing.JButton Button_checkout;
    private javax.swing.JButton bRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel totalSum;
    // End of variables declaration//GEN-END:variables
}
